### ISSUE TITLE
Expose programmatic way of loading a model

### ISSUE THREAD

**Issue by kibertoad** [nearform/fastify-casbin#2]
According to official documentation, it is possible to instantiate casbin model programmatically instead of loading it from file. See https://casbin.org/docs/en/model-storage#load-model-from-code

Would you be open to a PR that would implement support for the same in `fastify-casbin`?

**Comment by simoneb** [comment]
This is already possible, the only issue is that the name of the option `modelPath` is kinda off, because in practice what you provide can be anything that newEnforcer supports as the first argument, including an instance of a casbin model initialized in code.

**Comment by kibertoad** [comment]
@simoneb Types are wrong then. Can I submit a PR that would fix it then?

**Comment by simoneb** [comment]
absolutely! you may want to rename the argument to model, too. it will require a semver major but it would be a more accurate name

**Comment by kibertoad** [comment]
@simoneb Implemented it in backwards-compatible way, but if you prefer to only keep one param, can drop the `modelPath` and remove all the compatibility logic.
