### ISSUE TITLE
Plugin intermittently doesn't return any result

### ISSUE THREAD

**Issue by nagarjun** [nearform/fastify-casbin#44]
## Setup

* Fastify-casbin version: ^2.0.0
* Node version: 14.16.1
* Running on: Heroku
* Database: Heroku Postgres

## Issue Description

We observed that at times, calls to Fastify-casbin does not return any results despite the fact that the relevant records exit in the database Oddly enough, repeating the same call does return the expected results. For example, we call:

```TypeScript
const casbinRoles = await fastify.casbin.getFilteredNamedGroupingPolicy('g', 0, request.user?.id as string)
if (casbinRoles.length === 0) {
  return reply.internalServerError('Server error - unable to find user\'s roles.')
}
```

We notice that `casbinRoles` sometimes doesn't return any items but repeating the call does. While we are investigating the point of failure (database connection issue, Heroku, etc.) I just wanted to post this here to ask if anyone else has observed this behaviour in the past and if so, how did you solve it? Are there any known issues with the library? We've observed the same behaviour for other calls to other methods as well. Thanks.

**Comment by hails** [comment]
@nagarjun hi there,
Were you guys able to tackle down the issue? 
I tried to reproduce locally but to no avail.

**Comment by hsluoyz** [comment]
@fabian4 @foxzero-007 plz take a look

**Comment by simoneb** [comment]
Closing as stale. If this keep occurring feel free to reopen. In any case, this plugin is only a proxy to casbin, so if an issue exists it's most likely to be in casbin than this plugin.
