### ISSUE TITLE
Blue/green pattern for enforcer instance

### ISSUE THREAD

**Issue by kibertoad** [nearform/fastify-casbin#6]
One problem that current implementation has is that it's not really possible to do a drop-in replacement for a casbin enforcer, which can be useful in a scenario where full policy reload is necessary. Currently it is only possible via doing `await fastify.casbin.clearPolicy()` and then loading the policy again, which leaves present a window when no permissions are loaded open for rejecting perfectly valid requests.

Not sure what elegant solution is possible here. Maybe we could replace direct usage of enforcer instance with some kind of a container entity (exported out of this package as well), that allows one to pass new enforcer to it?

**Comment by simoneb** [comment]
Independently from how it's set up in this plugin, I'm not sure I see a case why the enforcer would need to be replaced. In which case would you need to replace the enforcer?

**Comment by kibertoad** [comment]
@simoneb Full reload. However, now that you've asked, I wonder if adjusting storage via adapter and then just calling `load` on enforcer would be perfectly sufficient for the use-case.

**Comment by simoneb** [comment]
Why would you need to do a full reload of the enforcer? I have a feeling that this goes beyond this plugin and it's probably a pattern that should not be used with Casbin. Casbin has many ways to load, change, filter, remove policies, so I'm not sure why you would ever want to replace the enforcer instance in the application. To make an analogy, take the fastify-postgres plugin. In my mind the issue you're raising here is similar to asking for a way to replace the instance of pg.Pool provided by that plugin. The question is, why would you ever want to do that?

**Comment by kibertoad** [comment]
@simoneb Yeah, in this particular case it probably is possible to solve the issue without replacing the enforcer.
To play devil's advocate - in fastify-postgres plugin case might actually want a way to replace pg.Pool on-the-fly if one is dealing with a roster of replicas, some of which may get created and destroyed over time.
